### PR TITLE
Fix -fpermissive build error

### PR DESCRIPTION
**Pull request by orbea**
Fixes the following build error with gcc-7.1.0.
```
../libretro/libretro.cpp:384:20: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
    if (codeline == '\0') return;
                    ^~~~
```
This was introduced in PR https://github.com/libretro/snes9x/pull/45.

After building snes9x successfully I tested cheats and they seem to work.

Also see https://github.com/libretro/bsnes-mercury/pull/48 and https://github.com/libretro/bsnes-libretro/pull/39 for related fixes.

### CODE REVIEW

**Comment by Sintendo** [comment]
Uh, wouldn't it make more sense to use NULL here?

**Comment by orbea** [comment]
Maybe, I'm not much of a programmer, but seems no one else is going to do it...

**Comment by orbea** [comment]
@Sintendo Do you think this is better?
```
diff --git a/libretro/libretro.cpp b/libretro/libretro.cpp
index 50a11ac..8bf696a 100644
--- a/libretro/libretro.cpp
+++ b/libretro/libretro.cpp
@@ -381,7 +381,7 @@ void retro_cheat_set(unsigned index, bool enabled, const char *codeline)
    char codeCopy[256];
    char* code;

-   if (codeline == (char *)'\0') return;
+   if (codeline == NULL) return;

    strcpy(codeCopy,codeline);
    code=strtok(codeCopy,"+,.; ");
```

**Comment by Sintendo** [comment]
Well, it depends. If the intention is to test for a null pointer, then I'd prefer we use ```NULL```.

However, the fact that ```'/0'``` was used makes me suspect that the intention may have been to check for an empty string (by checking if the first character is the NUL character) rather than a null pointer. In that case, the original code was wrong and forgot to dereference ```codeline```.  If so, we should instead write ```if (*codeline == '/0') return;``` or ```if (codeline[0] == '/0') return;```.

Perhaps @ilag11111 can explain which one is desirable? Perhaps neither is really needed and the line should be removed entirely?

**Comment by ilag11111** [comment]
The purpose and intended effect of the line is to prevent a crash or infinite loop when an empty code attempts to be applied.  There was little intelligence involved with its compositon; it was just the first thing that compiled on my machine and had the intended effect.  If there's a way to rewrite the line to be more proper, I don't know it.  I am not a C programmer; I only know just enough to be dangerous.

The correct replacement depends on how RA handles blank codes and passes them to retro_cheat_set.  If it passes NULL, then orbea is probably doing it right.  If it passes a pointer to '/0', Sintendo looks right.  Maybe combine both with || to be safe.

I'll try to make some time soon to improve this and spread it through all the cores I put this on.

**Comment by orbea** [comment]
@ilag11111 Could you specify your test cases for your cheat patches? It would be good to confirm it at least still works. :) I tried various cheats and they seem to work but as cheats are not part of my regular play style I am not sure if I tested the right ones or not.

**Comment by ilag11111** [comment]
Here's my test cheat file for Super Mario World (U).  Has a sample of each supported cheat format, a multiline cheat, and an empty code.  Other systems were tested in a similar way.
cheats = "6"
cheat0_desc = "RAW - Jump In Midair"
cheat0_enable = "true"
cheat0_code = "00D5F4:80"
cheat1_desc = "Genie - Coins Rack Up All The Time"
cheat1_enable = "true"
cheat1_code = "4064-ADD7"
cheat2_desc = "PAR - Infinite 99 Lives"
cheat2_enable = "true"
cheat2_code = "7E0DBE63"
cheat3_desc = "GF - Nighttime"
cheat3_enable = "true"
cheat3_code = "0770440XXXX5B0"
cheat4_desc = "Multiline - Infinite Time"
cheat4_enable = "true"
cheat4_code = "7E0F31:09+7E0F32:09+7E0F33:09"
cheat5_desc = "NULL"
cheat5_enable = "true"
cheat5_code = ""

**Comment by orbea** [comment]
Thanks, I tested that and all the cheats seem to work for me. :)
